x-environment: &common_environment
  - TZ: Asia/Seoul
  - MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  - MYSQL_REPLICATION_USER: $MYSQL_REPLICATION_USER
  - MYSQL_REPLICATION_PASSWORD: $MYSQL_REPLICATION_PASSWORD

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'

  mysql-master:
    image: bitnami/mysql
    networks:
      - default
    volumes:
      - ./my_custom_master.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
      - mysql_primary_data:/bitnami/mysql/data
    restart: always
    environment:
      <<: *common_environment
      MYSQL_REPLICATION_MODE: master
      MYSQL_USER: $MYSQL_USERNAME
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE

    ## 추후에 백엔드 서버도 도커로 구성하면, expose 로 수정하여 외부접근 차단 해야함
    ports:
      - '3306:3306'

  mysql-slave:
    image: bitnami/mysql
    volumes:
      - ./my_custom_slave.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
      - mysql_standby_data:/bitnami/mysql/data
    networks:
      - default
    restart: always
    ports:
      - '3307:3306'
    depends_on:
      - mysql-master
    environment:
      <<: *common_environment
      MYSQL_REPLICATION_MODE: slave
      MYSQL_MASTER_HOST: mysql-master
      MYSQL_MASTER_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

volumes:
  mysql_primary_data:
  mysql_standby_data:

networks:
  default:
    driver: bridge
