services:
  mysql-master:
    expose:
      - '3306'
  redis:
    expose:
      - '6379'
  server:
    build:
      context: .
    environment:
      DB_HOST: mysql-master
      REDIS_HOST: redis
      TEST_DB_HOST: ${TEST_DB_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_REPLICATION_USER: ${MYSQL_REPLICATION_USER}
      MYSQL_REPLICATION_PASSWORD: ${MYSQL_REPLICATION_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRETS: ${JWT_SECRETS}
      JWT_ACCESS_TOKEN_EXPIRED_TIME: ${JWT_ACCESS_TOKEN_EXPIRED_TIME}
      JWT_REFRESH_TOKEN_EXPIRED_TIME: ${JWT_REFRESH_TOKEN_EXPIRED_TIME}
    image: seokzoo/todo:latest
    # 공식문서 : https://docs.docker.com/reference/compose-file/deploy/
    deploy:
      replicas: 2
      mode: replicated # default value = replicated 임 근데, 그냥 공부 목적으로 씀
      endpoint_mode: vip
      restart_policy:
        condition: on-failure # 서버는 any 나 on-failure 쓰는걸 권장함
        delay: 5s
    depends_on:
      - redis
      - mysql-master
    ports:
      - '8081:8080'
