spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: todo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:5432/todo
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
