spring:
  profiles:
    default: local
  config:
    import: optional:file:.env[.properties]
  application:
    name: todo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

logging:
  level:
    org.springframework.cache: trace

jwt:
  secret: ${JWT_SECRETS}
  accessTokenExpiration: ${JWT_ACCESS_TOKEN_EXPIRED_TIME}
  refreshTokenExpiration: ${JWT_REFRESH_TOKEN_EXPIRED_TIME}
