spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: todo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost:6379
      password: ${REDIS_PASSWORD}
      port: 6379

jwt:
  secret: ${JWT_SECRETS}
  accessTokenExpiration: ${JWT_ACCESS_TOKEN_EXPIRED_TIME}
  refreshTokenExpiration: ${JWT_REFRESH_TOKEN_EXPIRED_TIME}
