spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: todo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test?serverTimezone=Asia/Seoul # 인메모리 모드를 통해 빠르게 데이터 로드 가능
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    redis:
      host: localhost
      port: 6380
  cache:
    type: redis

jwt:
  secret: ${JWT_SECRETS}
  accessTokenExpiration: ${JWT_ACCESS_TOKEN_EXPIRED_TIME}
  refreshTokenExpiration: ${JWT_REFRESH_TOKEN_EXPIRED_TIME}
